ADVYTEAM.Presentation/Controllers/ChatController.cs
using ADVYTEAM.Data;
using ADVYTEAM.Presentation.Models;
using ADVYTEAM.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ADVYTEAM.Presentation.Controllers
{
    public class ChatController : Controller
    {
        IUtilisateurService serviceUtilisateur;
        IMessageService messageService;
        UserVM userVm, userc , userch;
        utilisateur user;
        public ChatController()
        {
            serviceUtilisateur = new UtilisateurService();
            messageService = new MessageService();
       
        }
        public string envoiMessage(string message)
        {
            userc = Session["userConnected"] as UserVM;
            userch = Session["userchat"] as UserVM;

            message m = new message()
            {
                content = message,
                date = DateTime.Now,
                id_receiver = userch.id,
                id_sender = userc.id
            };

            this.messageService.Add(m);
            this.messageService.Commit();


            return discussion();
        }
        public string discussion()
        {
            userc = Session["userConnected"] as UserVM;
            userch = Session["userchat"] as UserVM;
              IEnumerable<message> lstM = this.messageService.GetMessagesBySenderReciver(userc.id, userch.id);
            //IEnumerable<message> lstM = this.messageService.GetMany(
            //                        message => (message.id_receiver == userc.id &&
            //                                   message.id_sender == userch.id) ||
            //                                   (message.id_receiver == userch.id &&
            //                                   message.id_sender == userc.id)
            //                        );
            var chaineM= "";
            foreach(message msg in lstM)
            {
                if (msg.id_sender == userc.id)
                {
                    chaineM += "<div class='direct-chat-msg right'>" +
                        "<div class='direct-chat-info clearfix'>" +
                            "<span class='direct-chat-timestamp float-left'>" + msg.date + "</span>" +
                        "</div>" +
                    "<img class='direct-chat-img' src='data:image/png;base64," + userc.image + "' alt='message user image'>" +
                        "<div class='direct-chat-text'>" +
                                msg.content+
                       "</div>" +
                    "</div>";
                }
                else
                {
                    chaineM += "<div class='direct-chat-msg'>" +
                                "<div class='direct-chat-info clearfix'>" +
                                "<span class='direct-chat-timestamp float-right'>" + msg.date + "</span>" +
                                "</div>" +
                                "<img class='direct-chat-img' src='data:image/png;base64," + userch.image + "' alt='message user image'>" +
                                "<div class='direct-chat-text'>" +
                                    msg.content +
                                "</div>" +
                                "</div>";
                }

            }

            return chaineM;
        }

        // GET: Chat
        public ActionResult Index(string idreciver )
        {
            userc = Session["userConnected"] as UserVM;
            user= this.serviceUtilisateur.GetById(System.Convert.ToInt32(idreciver));
            Session["userchat"] = userVm;
            userVm = new UserVM()
            {
                id = user.id,
                nom = user.nom,
                prenom=user.prenom,
                image=user.image
            };
            Session["userchat"] = userVm;
            ViewBag.userc = userc;
            return View(userVm);
        }

        // GET: Chat/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Chat/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Chat/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Chat/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Chat/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Chat/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Chat/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ChatRoom()
        {
            return View();
        }
    }
}

ADVYTEAM.Presentation/Controllers/LoginController.cs
using ADVYTEAM.Data;
using ADVYTEAM.Presentation.Models;
using ADVYTEAM.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Net.Mail;
using System.Web.Mvc;
using System.Security.Cryptography;
using System.Text;

namespace ADVYTEAM.Presentation.Controllers
{
    public class LoginController : Controller
    {
        HttpClient Client;
        HttpResponseMessage responce;
        utilisateur user;
        IUtilisateurService serviceUtilisateur;
        IList<UserVM> lstcontact;

        public LoginController()
        {
            serviceUtilisateur = new UtilisateurService();
            lstcontact = new List<UserVM>();
        }
        // GET: Login
        public ActionResult Index()
        {
            return View(user);
        }

        // GET: Login/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Login/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Login/Create
        [HttpPost]
        public ActionResult Create(LoginVM loginVm)
        {
            Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:9080");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            responce = Client.GetAsync("/PIDEV-web/PIDEV/gestionEmploye/login?login="+loginVm.login+"&pass="+loginVm.password).Result;
            if (responce.IsSuccessStatusCode)
            {

                user = responce.Content.ReadAsAsync<utilisateur>().Result;
 
                    UserVM u = new UserVM
                    {
                        prenom = user.prenom,
                        nom = user.nom,
                        image = user.image,
                        id = user.id
                    };
                    Session["userConnected"] = u;

                    foreach (utilisateur user in serviceUtilisateur.GetMany())
                    {
                        lstcontact.Add(new UserVM()
                        {
                            id = user.id,
                            nom = user.nom,
                            prenom = user.prenom,
                            image = user.image
                        });
                    }

                    Session["lstContact"] = lstcontact;

                    return Redirect("~/Publication/Index");
                  
            }
            return View();
            
        }

        public ActionResult LogOff()
        {
            Session.Contents.RemoveAll();

            return RedirectToAction("Create");
        }

        public ActionResult OubliePassword(LoginVM loginVm)
        {
 
                return View();
        }

        public ActionResult traiteCode(LoginVM loginVm)
        {
            utilisateur user = serviceUtilisateur.Get(u => u.email.Equals(loginVm.login));
            if (user != null)
            {
                Random aleatoire = new Random();
                int code = aleatoire.Next(1000, 9999);

 
                MailMessage mail = new MailMessage();
                SmtpClient SmtpServer = new SmtpClient("smtp.gmail.com");
                mail.From = new MailAddress("porjet2019@gmail.com");
                mail.To.Add(user.email);
                mail.Subject = "Oublié mot de passe";
                mail.Body = "Bonjour M/Mme " + user.nom + " " + user.prenom + "  Votre Code est : " + code;
                SmtpServer.Port = 587;
                SmtpServer.Credentials = new System.Net.NetworkCredential("porjet2019@gmail.com", "duwhjaxubkjxebih");
                SmtpServer.EnableSsl = true;
                SmtpServer.Send(mail);

                Session["mail"] = user.email;
                Session["code"] = code;
                Session["user"] = user;

                return RedirectToAction("newPassword");
            }
            else
                return View();
        }

        public ActionResult newPassword()
        {
            utilisateur u = Session["user"] as utilisateur;

         //   string email = Session["mail"].ToString();
            string code = Session["code"].ToString();

            oubliePass oublie = new oubliePass();
            oublie.email = u.email;

            return View(oublie);
        }

        public ActionResult changerPassword(oubliePass oublie)
        {
            utilisateur u = Session["user"] as utilisateur;
            int code = Int32.Parse(Session["code"].ToString());
            if (code == oublie.Code && oublie.password.Equals(oublie.confpassword)) {

                u.password = MD5Hash(oublie.password);

                serviceUtilisateur.Commit();

                return RedirectToAction("Create");
               
            } 
            return RedirectToAction("OubliePassword");
        }

        public static string MD5Hash(string text)
        {
            MD5 md5 = new MD5CryptoServiceProvider();

            md5.ComputeHash(ASCIIEncoding.ASCII.GetBytes(text));

            //get hash result after compute it  
            byte[] result = md5.Hash;

            StringBuilder strBuilder = new StringBuilder();
            for (int i = 0; i < result.Length; i++)
            {
                //change it into 2 hexadecimal digits  
                //for each byte  
                strBuilder.Append(result[i].ToString("x2"));
            }

            return strBuilder.ToString();
        }
    }
}

ADVYTEAM.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom d'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)
</body>
</html>

ADVYTEAM.Presentation/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V18</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     
    <link rel="icon" type="image/png" href="~/Content/images/icons/favicon.ico" />

    @Styles.Render("~/login/css")
     
</head>
<body style="background-color: #666666;">
    @RenderBody()

    @Scripts.Render("~/login/script")
    @RenderSection("scripts", required: false)
</body>
</html>

ADVYTEAM.Presentation/Views/Shared/_templateLayout.cshtml
@using ADVYTEAM.Presentation.Models
@{ 

    UserVM userc = Session["userConnected"] as UserVM;
      List<UserVM> lstcontact = Session["lstContact"] as List<UserVM>;

}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title></title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    @Scripts.Render("~/bundles/jquery")
    <script src="https://code.jquery.com/jquery-3.4.0.js"></script>
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/chosen/1.1.0/chosen.min.css">

    <!-- JS -->
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/chosen/1.1.0/chosen.jquery.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/chosen/1.1.0/chosen.jquery.js"></script>
    <!-- jQuery UI CSS File -->
    <link href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.min.css" rel="stylesheet" type="text/css" />
    <!-- jQuery Reference -->
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <!-- jQuery UI Reference -->
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.min.js"></script>
    @Styles.Render("~/template/css")
    <title>@ViewBag.Title - ADVYTEAM</title>

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")
    @*<title>@ViewBag.Title - ADVYTEAM</title>*@



</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="index3.html" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Contact</a>
                </li>
            </ul>

            <!-- SEARCH FORM -->
            <form class="form-inline ml-3">
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Messages Dropdown Menu -->
                <!-- Notifications Dropdown Menu -->

                <li class="nav-item">
                    <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
                        <i class="fa fa-th-large"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <div class="brand-link">
                <img src="../../Content/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">

                <span class="brand-text font-weight-light">Déconnexion </span>
                <input type="submit" onclick="location.href='@Url.Action("LogOff","Login")'" class="btn btn-default" value="LogOut" />
            </div>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="data:image/jpeg;base64,@userc.image" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block"> @userc.nom - @userc.prenom </a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        <li class="nav-item has-treeview menu-open">
                            <a href="#" class="nav-link active">
                                <i class="nav-icon fa fa-dashboard"></i>
                                <p>
                                    Starter Pages
                                    <i class="right fa fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="#" class="nav-link active">
                                        <i class="fa fa-circle-o nav-icon"></i>
                                        <p>Active Page</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="fa fa-circle-o nav-icon"></i>
                                        <p>Inactive Page</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fa fa-th"></i>
                                <p>
                                    Simple Link
                                    <span class="right badge badge-danger">New</span>
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>


        <div class="content-wrapper">

            @RenderBody()

        </div>


        <!-- Control Sidebar -->

        <aside class="control-sidebar control-sidebar-dark scrollbar">

            @{Html.RenderPartial("ListContact");}

            @*@foreach (var p in lstcontact)
                {
                    <div class="user-panel mt-3 pb-3 mb-3 d-flex aside-contact">
                        <div class="image">
                            <img src="data:image/png;base64,@p.image"
                                 class="img-circle elevation-2" alt="User Image" />
                        </div>
                        </div>
                 }*@


        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

    <script type="text/javascript">
        $(document).ready(function () {
            $(".control-sidebar").height($(window).height() - 57);
            window.onscroll = function () {
                if ($('.control-sidebar').is(':visible')) {
                    $(".control-sidebar").css({ position: "fixed" });
                    if (document.body.scrollTop > 57 || document.documentElement.scrollTop > 57) {
                        $(".control-sidebar").css({ top: "0px" });
                    } else {
                        $(".control-sidebar").css({ position: "", top: "57px" });
                    }
                } else {
                    $(".control-sidebar").css({ position: "" });
                }

            };
        });


    </script>
    @Scripts.Render("~/template/script")
    @RenderSection("scripts", required: false)
    @RenderSection("MyScripts", required: false)
    


</body>
</html>

ADVYTEAM.Presentation/Views/Shared/listContact.cshtml
@using ADVYTEAM.Presentation.Models
@{

    List<UserVM> lstcontact = Session["lstContact"] as List<UserVM>;

}


@foreach (var p in lstcontact)
{
    <div class="user-panel mt-3 pb-3 mb-3 d-flex aside-contact">
        <div class="image">
            <img src="data:image/png;base64,@p.image"
                 class="img-circle elevation-2" alt="User Image" />
        </div>
        <div class="info">
            <a href="@Url.Action("Index", "Chat", new { idreciver = @p.id })" class="d-block">
                @p.nom @p.prenom
            </a>
        </div>
    </div>
}