ADVYTEAM.Presentation/Controllers/SurveyController.cs
using ADVYTEAM.Data;
using ADVYTEAM.Domain.Entities;
using ADVYTEAM.Presentation.Models;
using ADVYTEAM.Services;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ADVYTEAM.Presentation.Controllers
{
    public class SurveyController : Controller
    {
        readonly HttpClient Client = new HttpClient();
        static List<SurveyQuestion> questions = new List<SurveyQuestion>();
       
        UtilisateurService us = new UtilisateurService();
        SurveyService  surveyservice;
        ISurveyQuestionService surquestservice;
        SurveyQuestEmpService surveyquestempservice;

        public SurveyController()
        {
           this.Client.BaseAddress = new Uri("http://localhost:9080/PIDEV-web/");
            this.Client.DefaultRequestHeaders.Accept.
                Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            surveyservice = new SurveyService();
            surquestservice = new SurveyQuestionService();
            surveyquestempservice = new SurveyQuestEmpService();
        }
        // GET: Survey
        public ActionResult Index()
        {
            List<SurveyVM> surveysvm = new List<SurveyVM>();
            IEnumerable<Survey> surveys = surveyservice.GetSurveysByMan(2);

            List<Survey> surveyslist = new List<Survey>();
            if (surveys.Count() == 1)
                surveyslist.Add(surveys.First());
            else
            {
                foreach (var surv in surveys)
                {
                    surveyslist.Add(new Survey
                    {
                        date = surv.date,
                        duree = surv.duree,
                        //employe = surv.employe,
                        employeId = surv.employeId,
                        //manager = surv.manager,
                        managerId = surv.managerId,
                        status = surv.status,
                        // SurveyQuestions = surv.SurveyQuestions
                    });
                }
            }
            foreach (var survey in surveyslist)
            {
                surveysvm.Add(new SurveyVM
                {
                    date = survey.date,
                    duree = survey.duree,
                    employe_id = survey.employeId,
                    manager_id = survey.managerId,
                    employee_Name = us.GetById((int)survey.employeId).nom +"  " +us.GetById((int)survey.employeId).prenom,
                    status = true ? "Underway" : "Off"
                });

                if(DateTime.Compare(survey.date.Value.AddDays(survey.duree), DateTime.Now) < 0)
                {
                    Survey su = surveyservice.Get(s => s.date == survey.date && s.employeId == survey.employeId && s.managerId == survey.managerId);
                    su.status = false;
                    surveyservice.Update(su);
                    surveyservice.Commit();
                }
            }
            
           
            return View(surveysvm);

        
        }

        // GET: Survey/Details/5
        public ActionResult Details(long empid, long manid, DateTime date)
        {
            Survey svy = surveyservice.Get(s => s.date == date && s.employeId == empid && s.managerId == manid);

            SurveyVM suvm = new SurveyVM
            {
                date = svy.date,
                duree = svy.duree,
                employe_id = svy.employeId,
                manager_id = svy.managerId,
                employee_Name = us.GetById((int)svy.employeId).nom + "  " + us.GetById((int)svy.employeId).prenom,
                status = "Underway"
            };

            ViewData["questions"] = svy.SurveyQuestions.ToList();
            

            return View(suvm);
        }

        // GET: Survey/Create
        public ActionResult Create()
        {
            //var dest = FormMethod.Get[]
           

            IEnumerable<utilisateur> employesnum = us.GetEmployesByman(2);
            List<utilisateur> employesList = new List<utilisateur>();
            foreach (var employe in employesnum)
            {
                employesList.Add(employe);
            }

                ViewData["employes"] = employesList;


            return View();
        }

        // POST: Survey/Create
        [HttpPost]
        public ActionResult Create(SurveyVM suv, string employename)
        {
            IEnumerable<utilisateur> employesnum = us.GetEmployesByman(2);
            List<utilisateur> employesList = new List<utilisateur>();
            foreach (var employe in employesnum)
            {
                employesList.Add(employe);
            }

            ViewData["employes"] = employesList;

            int empid = System.Convert.ToInt32(employename.Substring(0, 1));

            
           try
            {
                if (questions.Count() == 0)
                {
                    ModelState.AddModelError("", "Ajouter des questions !");
                    return View();
                }
                else
                {
                    foreach (SurveyQuestion quest in questions)
                    {
                        quest.date = DateTime.Now; quest.employeId = empid; quest.managerId = 2;
                        //surquestservice.Add(quest);
                    }

                    List<SurveyQuestion> questionlist = new List<SurveyQuestion>();
                    questionlist = questions;


                    foreach (SurveyQuestion quest in questionlist)
                    {
                        quest.date = DateTime.Now; quest.employeId = empid; quest.managerId = 2;
                        surquestservice.Add(quest);
                    }
                    Survey sv = new Survey() { date = DateTime.Now, duree = suv.duree, status = true, managerId = 2, employeId = empid };

                    surveyservice.Add(sv);
                    surveyservice.Commit();
                    surquestservice.Commit();
                    questions.Clear();

                    return RedirectToAction("Index");
                }
            }
            catch(Exception e)
            {
               // Console.WriteLine(e.Message);
              
                return View(e.Message);
            }
        }

        // GET: Survey/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Survey/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Survey/Delete/5
        public ActionResult Delete(long empid, long manid, DateTime date)
        {
            //try { 
            Survey sur = surveyservice.Get(s => s.date == date && s.employeId == empid && s.managerId == manid);
            List<SurveyQuestion> surquests1 = new List<SurveyQuestion>();

            foreach (var surquest in sur.SurveyQuestions)
            {
                surquests1.Add(new SurveyQuestion
                {
                    id = surquest.id,
                    date = surquest.date,
                    //employe = surv.employe,
                    employeId = surquest.employeId,
                    //manager = surv.manager,
                    managerId = surquest.managerId,
                    // SurveyQuestions = surv.SurveyQuestions
                });
            }
            surquestservice.Commit();
            surveyservice.Delete(sur);
            foreach (var question in surquests1)
            {
                SurveyQuestion qs = surquestservice.Get(s => s.id == question.id);
                surquestservice.Delete(qs);
                surquestservice.Commit();
            }

            surveyservice.Delete(sur);

            
            surveyservice.Commit();

            return RedirectToAction("Index");
       /* }
             catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
                return View();
            }*/
        }

        // POST: Survey/Delete/5
        [HttpPost]
        public ActionResult Delete( FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult UpdateSkills(string userid)
        {
            Task<string> task = Client.GetAsync("PIDEV/evaluation/skill/"+userid.Substring(0,1)).Result.Content.ReadAsStringAsync();
            task.Wait();
            string responseStr = task.Result;

            List<skill> skills = JsonConvert.DeserializeObject<List<skill>>(responseStr);

     
            if (Request.IsAjaxRequest())
            return Json(skills, JsonRequestBehavior.AllowGet);

            return null;
        }

        [HttpGet]
        public ActionResult UpdateQuestions(string text)
        {
            
            questions.Add(new SurveyQuestion() {  question = text });

            //if (Request.IsAjaxRequest())
                return Json(questions, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public ActionResult ClearQuestions()
        {

            questions.Clear();

            //if (Request.IsAjaxRequest())
            return Json(questions, JsonRequestBehavior.AllowGet);

        }

        public ActionResult StatByQuestion(int questid)
        {
            SurveyQuestion sq = surquestservice.Get(s =>s.id == questid);

ADVYTEAM.Presentation/Views/Survey/Create.cshtml
@model ADVYTEAM.Presentation.Models.SurveyVM
@using ADVYTEAM.Data;


@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create","Survey",FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4 id="survey">Survey</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">Days of duration</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.duree, new { htmlAttributes = new { @class = "form-control" , @required = "true"} })
            @Html.ValidationMessageFor(model => model.duree, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">

        <div class="col-md-10">
            <label class="control-label col-md-2">Employee</label> <select class="chosen" id="employes" name="employename">

                @foreach (var std in ViewData["employes"] as IList<utilisateur>)
                {
                    <option>
                        <b style="display :none">@std.id .</b>  @std.nom    @std.prenom
                    </option>

                }
            </select>
           <label class="control-label col-md-2"> Skills : </label><b id="skillslist"></b>
        </div>
    </div>
   
       
            <label class="control-label col-md-2">Question</label><input class = "form-control" type="text" id="question"/><a class="btn-group" id="addquest" href="#">Add</a>
        
    <hr>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create"  class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div style="float:left">
    @Html.ActionLink("Back to List", "Index")
</div>

<div style="float:right">
    <h4 style="font-weight:bold">Liste des questions</h4>
    <ul id="questionlist">
    </ul>
    <button class="btn-group" id="clearlist">Clear</button>
</div>



<script type="text/javascript">
   
    $(document).ready(function () {
        //$(".chosen").chosen();
        $('#employes').change(function () {
            var employee_Name = $("#employes").val();
            console.log(employee_Name);
            $('#skillslist').empty();
            $.ajax({
                type: "GET",
                url: "UpdateSkills?userid=" + employee_Name,
                dataType: "json",

                success: function (data) {
                    if (data != null && !jQuery.isEmptyObject(data)) {

                        var skillsSelect = $('#skillslist');

                        $.each(data, function (index, skill) {
                            skillsSelect.append(skill.name + "  -");
                        });
                    }
                },
                error: function (xhr, status, error) {
                    console.log(error);
                }
            });
        });

        $('#addquest').click(function () {
            var questiontext = $("#question").val();
            if (questiontext != "") {
                $.ajax({
                    type: "GET",
                    url: "UpdateQuestions?text=" + questiontext,
                    dataType: "json",

                    success: function (data) {
                        $("#questionlist").empty();
                        $.each(data, function (index, question) {
                            console.log(question.question);
                            $("#questionlist").append($('<li>' + question.question + '</li>'));
                        });
                        
                    },
                    error: function (xhr, status, error) {
                        console.log(error);
                    },
                });
                }
        });
        $('#clearlist').click(function () {
            
                $.ajax({
                    type: "GET",
                    url: "ClearQuestions",
                    dataType: "json",

                    success: function (data) {
                        $("#questionlist").empty();
                       
                    },
                    error: function (xhr, status, error) {
                        console.log(error);
                    },
                });
               
        });
            });
   
    
   

    </script>

ADVYTEAM.Presentation/Views/Survey/Details.cshtml
@model ADVYTEAM.Presentation.Models.SurveyVM
@using ADVYTEAM.Domain.Entities;


@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Survey of  @Html.DisplayFor(model => model.employee_Name) ( @Html.DisplayFor(model => model.date) /   @Html.DisplayFor(model => model.duree)  jours)</h4>
    <hr />
    <dl class="dl-horizontal">
        @{int i = 1;}
        @foreach (var std in ViewData["questions"] as IList<SurveyQuestion>)
        {
            <dd>Question  @i :</dd>
            <dt>
                @std.question
            
            </dt>
           <p style="font-size:12px"> @Html.ActionLink("View stats", "StatByQuestion", new { questid = std.id }) </p>

            i = i + 1;

            <hr />
        }

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

ADVYTEAM.Presentation/Views/Survey/Index.cshtml
@model IEnumerable<ADVYTEAM.Presentation.Models.SurveyVM>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.duree)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.status)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.employee_Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.date)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.duree)   <b>jours</b>
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.status)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.employee_Name)
    </td>
    <td>
        @Html.ActionLink("Details", "Details", new { empid = item.employe_id, manid = item.manager_id, date = item.date }) |
        <!--@Html.ActionLink("Delete", "Delete", new { empid = item.employe_id, manid = item.manager_id, date = item.date })-->
    </td>
</tr>
}

</table>

ADVYTEAM.Presentation/Views/Survey/StatByQuestion.cshtml
@model ADVYTEAM.Presentation.Models.SurveyQuestionVM

@{
    ViewBag.Title = "StatByQuestion";
}

<h2>Stats By Question</h2>

<div>
    <h4>Question : @Html.DisplayFor(model => model.question)</h4>
    <hr />
    <dl class="dl-horizontal">
        <div  id="chartContainer" style="height: 500px; width: 500px"></div>
    </dl>
</div>


<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
<script>
   window.onload = function (){

var chart = new CanvasJS.Chart("chartContainer", {
	theme: "light1", // "light1", "light2", "dark1", "dark2"
	exportEnabled: true,
	animationEnabled: true,
	title: {
		text: "Statistics"
	},

	data: [{
		type: "pie",
		startAngle: 180,
		toolTipContent: "<b>{label}</b>: {y}",
		showInLegend: "true",
		legendText: "{label}",
		indexLabel: "{label} - {y}",
		dataPoints: @Html.Raw(ViewData["datapoints"])
	}]
});
    chart.render();

}
</script>

ADVYTEAM.Presentation/Views/Survey/UpdateSkills.cshtml
@{
    ViewBag.Title = "UpdateSkills";
}

<h2>UpdateSkills</h2>

<b id="here">fdsfdsa</b>

<script>
     $(document).ready(function () {    
            $('#here').click(function () {
               // var employee_Name = $("#employes").val();
                $.ajax({
    type: "GET",
    url: "UpdateSkills",
    dataType: "json",

    success: function(data) {
         alert("success");
    },
    error: function(xhr,status,error){
        console.log(error);
    }
});
            });
    });
</script>