ADVYTEAM.Presentation/Controllers/ReclamationController.cs
using ADVYTEAM.Data;
using ADVYTEAM.Domain.Entities;
using ADVYTEAM.Presentation.Models;
using ADVYTEAM.Services;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ADVYTEAM.Presentation.Controllers
{
    public class ReclamationController : Controller
    {
 
        IEnumerable<reclamation> lstRecl;
        IEnumerable<reclamation> lstReclt;
        IEnumerable<reclamation> lstReclc;
        IEnumerable<reclamation> lstRecln;
        IReclamationService serviceReclamation;
        IUtilisateurService serviceUtilisateur;

        public ReclamationController()
        {
            serviceReclamation = new ReclamationService();
            serviceUtilisateur = new UtilisateurService();
 
        }

        public ActionResult updateRecl(int id)
        {
            reclamation r = serviceReclamation.Get(f => f.Id == id);
            utilisateur us = serviceUtilisateur.Get(user => user.id == r.UserId);

            if (r.Etat == 0)
                r.Etat = 1;
            else if (r.Etat == 1)
            {
                r.Etat = 2;
                r.DateTraitement = DateTime.Now;
            }

            foreach (reclamation rec in us.Reclamations)
            {
             if(rec.Id==id)
                {
                    if (rec.Etat == 0)
                        rec.Etat = 1;
                    else if (rec.Etat == 1) { 
                        rec.Etat = 2;
                    rec.DateTraitement=DateTime.Now;
                }
                }
            } 
            serviceUtilisateur.Commit();
            return RedirectToAction("Index");
        }


        public ActionResult MesReclamation()
        {
            UserVM userc = Session["userConnected"] as UserVM;

            //   lstRecl = serviceReclamation.GetMany(reclamation=>reclamation.UserId== userc.id);
            lstRecl = serviceReclamation.GetMesReclmations(userc.id);

            foreach (var rec in lstRecl)
            {
                rec.Utilisateur = serviceUtilisateur.GetById((int)rec.UserId);
            }
            ViewBag.listReclamtion = lstRecl;

            return View();
        }


            // GET: Reclamation
        public ActionResult Index()
        {
            lstRecl = null;
            UserVM userc = Session["userConnected"] as UserVM;
            if (userc == null)
                return RedirectToAction("Create", "Login");

            lstRecln = serviceReclamation.GetReclmationsAttent();
            lstReclc = serviceReclamation.GetReclmationsEnCour();
            lstReclt = serviceReclamation.GetReclmationsTraite();
            // lstRecl = serviceReclamation.GetMany();
            foreach (var rec in lstRecln)
            {
                rec.Utilisateur = serviceUtilisateur.GetById((int)rec.UserId);
            }
            foreach (var rec in lstReclc)
            {
                rec.Utilisateur = serviceUtilisateur.GetById((int)rec.UserId);
            }
            foreach (var rec in lstReclt)
            {
                rec.Utilisateur = serviceUtilisateur.GetById((int)rec.UserId);
            }
            ViewBag.reclamationAttnte = lstRecln;
            ViewBag.reclamationCours = lstReclc;
            ViewBag.reclamationTraite= lstReclt;


            return View();
        }

        // GET: Reclamation/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Reclamation/Create
        public ActionResult Create()
        {
            UserVM userc = Session["userConnected"] as UserVM;
            if (userc == null)
                return RedirectToAction("Create", "Login");
            else

            return View();
        }

        // POST: Reclamation/Create
        [HttpPost]
        public ActionResult Create(ReclamationVM reclamationVM)
        {
            UserVM userc = Session["userConnected"] as UserVM;

            if (ModelState.IsValid)
            {
                reclamation r = new reclamation()
                {
                    Objet = reclamationVM.Objet,
                    Description = reclamationVM.Description,
                    DateReclamation = DateTime.Now,
                    DateTraitement = null,
                    Etat = 0,
                    UserId = userc.id
                    
                };

              //  serviceReclamation.Add(r);
              //  serviceReclamation.Commit();
                utilisateur user = serviceUtilisateur.GetById((int)userc.id);
                user.Reclamations.Add(r);
                serviceUtilisateur.Commit();
 

                return RedirectToAction("MesReclamation");
            }
            return View();
        }

        // GET: Reclamation/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Reclamation/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reclamation/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Reclamation/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ADVYTEAM.Presentation/Views/Reclamation/Create.cshtml
@model ADVYTEAM.Presentation.Models.ReclamationVM


@using  (Html.BeginForm("Create", "Reclamation") ) 
{
    @Html.AntiForgeryToken()
    
    <div class="card-body">



        <div class="form-group">
            @Html.LabelFor(model => model.Objet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Objet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Objet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>



 
        <div class="card-footer">
            <input type="submit" value="Réclamer" class=" btn btn-primary float-right" />

        </div>
    </div>
}

 

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

ADVYTEAM.Presentation/Views/Reclamation/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<br />
<h3>Liste des réclamations</h3>
<br />
<section class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-10">
                <!-- Custom Tabs -->
                <div class="card">
                    <div class="card-header d-flex p-0">
                        <h3 class="card-title p-3"> </h3>
                        <ul class="nav nav-pills ml-auto p-2">
                            <li class="nav-item"><a class="nav-link active" href="#tab_1" data-toggle="tab">En attent</a></li>
                            <li class="nav-item"><a class="nav-link" href="#tab_2" data-toggle="tab">En cour de traitement</a></li>
                            <li class="nav-item"><a class="nav-link" href="#tab_3" data-toggle="tab">traitée</a></li>
                        </ul>
                    </div><!-- /.card-header -->
                    <div class="card-body">
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab_1">
                                @foreach (var p in ViewBag.reclamationAttnte)
                                {
                                    <div class="card card-widget">
                                        <div class="card-header">
                                            <div class="user-block">
                                                <img class="img-circle" src="data:image/jpeg;base64,@p.Utilisateur.image" alt="User Image">
                                                <span class="username">
                                                    <a href="#">@p.Utilisateur.prenom @p.Utilisateur.nom </a>

                                                </span>

                                                <span class="description">
                                                    Date réclamation - @p.DateReclamation

                                                </span>
                                            </div>
                                        </div>
                                        <div class="card-body">
                                            <p>
                                                Objet: @p.Objet
                                            </p>

                                            <div class=" card-comments">
                                                <div class="comment-text">
                                                    Description :   @p.Description
                                                </div>
                                            </div>

                                            @*<a href="@Url.Action("updateRecl", "Reclamation", new { id = @p.Id })" class="badge badge-warning float-right" data-widget="remove">
                                                traiter 
                                            </a>*@
                                        <button type="button" onclick="location.href='@Url.Action("updateRecl", "Reclamation", new { id = @p.Id })'" class="badge badge-warning float-right">
                                            traiter
                                        </button>
                                        </div>

                                    </div>

                                }
                            </div>
                            <!-- /.tab-pane -->
                            <div class="tab-pane" id="tab_2">
                                @foreach (var p in ViewBag.reclamationCours)
                                {
                                    <div class="card card-widget">
                                        <div class="card-header">
                                            <div class="user-block">
                                                <img class="img-circle" src="data:image/jpeg;base64,@p.Utilisateur.image" alt="User Image">
                                                <span class="username">
                                                    <a href="#">@p.Utilisateur.prenom @p.Utilisateur.nom </a>

                                                </span>

                                                <span class="description">
                                                    Date réclamation - @p.DateReclamation

                                                </span>
                                            </div>
                                        </div>
                                        <div class="card-body">
                                            <p>
                                                Objet: @p.Objet
                                            </p>

                                            <div class=" card-comments">
                                                <div class="comment-text">
                                                    Description :   @p.Description
                                                </div>
                                            </div>

                                       
                                            <button type="button" onclick="location.href='@Url.Action("updateRecl", "Reclamation", new { id = @p.Id })'" class="badge badge-info float-right">
                                                traiter
                                            </button>
                                        </div>

                                    </div>
                                }
                            </div>
                            <!-- /.tab-pane -->
                            <div class="tab-pane" id="tab_3">
                                @foreach (var p in ViewBag.reclamationTraite)
                                {
                                    <div class="card card-widget">
                                        <div class="card-header">
                                            <div class="user-block">
                                                <img class="img-circle" src="data:image/jpeg;base64,@p.Utilisateur.image" alt="User Image">
                                                <span class="username">
                                                    <a href="#">@p.Utilisateur.prenom @p.Utilisateur.nom </a>

                                                </span>

                                                <span class="description">
                                                    Date réclamation - @p.DateReclamation
                                                    Date traitement - @p.DateTraitement
                                                </span>
                                            </div>
                                        </div>
                                        <div class="card-body">
                                            <p>
                                                Objet: @p.Objet
                                            </p>
                                            <div class=" card-comments">
                                                <div class="comment-text">
                                                    Description @p.Description
                                                </div>
                                            </div>
 
                                        </div>

                                    </div>

                                }

                            </div>
                            <!-- /.tab-pane -->
                        </div>
                        <!-- /.tab-content -->
                    </div><!-- /.card-body -->
                </div>
                <!-- ./card -->
            </div>
            <!-- /.col -->
        </div>

    </div>
</section>

ADVYTEAM.Presentation/Views/Reclamation/MesReclamation.cshtml
@using ADVYTEAM.Presentation.Models
@{
    ViewBag.Title = "MesReclamation";
    UserVM userc = Session["userConnected"] as UserVM;
}

<br />
<h1>Mes réclamations</h1>
<br />

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9">


                <div class="card card-primary">
                    <div class="card-header">
                        <div class="user-block">
                            <img class="img-circle"
                                 src="data:image/jpeg;base64,@userc.image" alt="User Image" />
                            <span class="username">
                                <a href="#">
                                    Ajouter
                                    une réclamation
                                </a>
                            </span>
                        </div>

                    </div>
                    @{Html.RenderPartial("Create");}
                </div>


                <div class="card-body p-0">
                    <ul class="products-list product-list-in-card pl-2 pr-2">
                        @foreach (var p in ViewBag.listReclamtion)
                        {
                            <li class="item">
                                <div class="product-img">

                                    <img src="~/Content/logo.jpg" alt="Product Image" class="img-size-50">

                                </div>
                                <div class="product-info">
                                    <a href="javascript:void(0)" class="product-title">
                                        Objet :   @p.Objet

                                        @if (@p.Etat == 0)
                                        {
                                            <span class="badge badge-warning float-right">En attent </span>
                                        }
                                        else if (@p.Etat == 1)
                                        {
                                            <span class="badge badge-info float-right">En Cour de traitement</span>
                                        }
                                        else
                                        {
                                            <span class="badge badge-success float-right">traitée</span>
                                        }

                                    </a>
                                    <span class="product-description">
                                        Description:   @p.Description
                                    </span>


                                </div>

                                <span class="text-muted float-right">Date réclamation @p.DateReclamation</span>
                            </li>
                        }
                    </ul>

                </div>


            </div>

        </div>



    </div>
</section>