ADVYTEAM.Presentation/Controllers/PublicationController.cs
using ADVYTEAM.Data;
using ADVYTEAM.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace ADVYTEAM.Presentation.Models
{
    public class PublicationController : Controller
    {
        IPublicationService publicationService;
       

        public PublicationController()
        {
            publicationService = new PublicationService();
             
        }

            // GET: Publication
            public ActionResult Index()
        {
            UserVM userc = Session["userConnected"] as UserVM;
            if (userc == null)
                return RedirectToAction("Create", "Login");

            Session["emp"] = userc.image;
            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:9080");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage responce = Client.GetAsync("/PIDEV-web/PIDEV/gestionEmploye/publication").Result;
       //     HttpResponseMessage responce2, responce3;
            if (responce.IsSuccessStatusCode)
            {
                IEnumerable<PublicationVM> lstPub = responce.Content.ReadAsAsync<IEnumerable<PublicationVM>>().Result;
                ViewBag.result = lstPub;
            }
            else
            {
                ViewBag.result = "error";
            }          

            return View();
        }

        // GET: Publication/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Publication/Create
        public ActionResult Create()
        {
            UserVM userc = Session["userConnected"] as UserVM;
            if (userc == null)
                return RedirectToAction("Create", "Login");
            return View();
        }

        // POST: Publication/Create
        [HttpPost]
        public ActionResult Create(PublicationVM publicationvm)
        {
            UserVM userc = Session["userConnected"] as UserVM;
            Session["emp"] = userc.image;

            publication p = new publication()
            {
                description=publicationvm.description,
                id_user = userc.id

            };

            HttpClient client = new HttpClient();

            HttpRequestMessage requestMessage = new HttpRequestMessage(HttpMethod.Post, "http://localhost:9080/PIDEV-web/PIDEV/gestionEmploye/publication");
            //requestMessage.Headers.Add("Authorization", "key=AAAAG...:APA91bH7U...");
            string json = new JavaScriptSerializer().Serialize(new
            {
                description = p.description,
                user = new { id = userc.id }
            });

            requestMessage.Content = new StringContent(json, Encoding.UTF8, "application/json");
           
            HttpResponseMessage response = client.SendAsync(requestMessage).GetAwaiter().GetResult();
            return RedirectToAction("Index");

        }

        // GET: Publication/Edit/5
        public ActionResult Edit(int id)
        {
            UserVM userc = Session["userConnected"] as UserVM;
            if (userc == null)
                return RedirectToAction("Create", "Login");


            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:9080");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage responce = Client.GetAsync("/PIDEV-web/PIDEV/gestionEmploye/publication/"+id).Result;

            PublicationVM Pub = responce.Content.ReadAsAsync<PublicationVM>().Result;

            ViewBag.userimg = userc.image;


            return View(Pub);
        }

        // POST: Publication/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, PublicationVM publicationVM)
        {

            publication pub = publicationService.GetById(id);
            pub.description = publicationVM.description;

            publicationService.Update(pub);
            publicationService.Commit();


                return RedirectToAction("Index");
            
        }

        // GET: Publication/Delete/5
        public ActionResult Delete(int id)
        {

            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:9080");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage responce = Client.DeleteAsync("/PIDEV-web/PIDEV/gestionEmploye/publication/"+id).Result;
            return RedirectToAction("Index");

        }

        // POST: Publication/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

ADVYTEAM.Presentation/Views/Publication/Create.cshtml
@model ADVYTEAM.Presentation.Models.PublicationVM



@using (Html.BeginForm("Create", "Publication"))
{
    @Html.AntiForgeryToken()

    <div class="card-body">


        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">


            @* @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.TextAreaFor(model => model.description, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })

        </div>

    </div>

    <div class="card-footer">
        <input type="submit" value="Publier" class=" btn btn-primary float-right" />

    </div>


}

ADVYTEAM.Presentation/Views/Publication/Edit.cshtml
        @model ADVYTEAM.Presentation.Models.PublicationVM

        @{
            ViewBag.Title = "Edit";
        }

<br /><br />
        <section class="content">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-md-9">
                        <div class="card card-primary">
                            <div class="card-header">
                                <div class="user-block">
                                    <img class="img-circle"
                                         src="data:image/jpeg;base64,@ViewBag.userimg" alt="User Image" />
                                    <span class="username">
                                        <a href="#">
                                            Modifier une publication
                                        </a>
                                    </span>
                                </div>
                            </div>


                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="card-body">

                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    <div class="form-group">

                                        @Html.TextAreaFor(model => model.description, new { @class = "form-control" })
                                        @*@Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })*@
                                        @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                                    </div>


                                    @Html.HiddenFor(model => model.id)
                                    </div>
                                    <div class="card-footer">
                                        <input type="submit" value="Modifier" class=" btn btn-primary float-right" />

                                    </div>
                                
                            }

                        </div>
                    </div>
                </div>
            </div>
        </section>

ADVYTEAM.Presentation/Views/Publication/Index.cshtml
@using ADVYTEAM.Presentation.Models
@{

    UserVM userc = Session["userConnected"] as UserVM;
    

}
<!-- Main content -->
<br />
<br />
<section class="content">
    <div class="container-fluid">
        
        <div class="row">
            <div class="col-md-9">
                <div class="card card-primary">
                    <div class="card-header">
                        <div class="user-block">
                            <img class="img-circle"
                                 src="data:image/jpeg;base64,@userc.image" alt="User Image" />
                            <span class="username">
                                <a href="#">
                                    créer
                                    une publication
                                </a>
                            </span>
                        </div>
                    </div>
                    @{Html.RenderPartial("Create");}

                </div>
                @foreach (var p in ViewBag.result)
                {
                    <!-- Box Comment -->
                    <div class="card card-widget">
                        <div class="card-header">
                            <div class="user-block">
                                <img class="img-circle" src="data:image/jpeg;base64,@p.user.image" alt="User Image">
                                <span class="username">
                                    <a href="#">@p.user.prenom @p.user.nom .</a>

                                </span>

                                <span class="description">
                                    Shared publicly - @p.dateCreation

                                </span>
                            </div>
                            <!-- /.user-block -->
                            @if (userc.id==@p.user.id)
                            {

                                <div class="card-tools">

                                    <a href="@Url.Action("Edit", "Publication", new { id = @p.id })" class="btn btn-tool" data-widget="remove">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a href="@Url.Action("Delete", "Publication", new { id = @p.id })" class="btn btn-tool" data-widget="remove" onclick="return confirm('Are you sure you want to delete this item?');">
                                        <i class="fas fa-trash"></i>
                                    </a>


                                </div>
                            }

                            <!-- /.card-tools -->
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <!-- post text -->
                            <p>
                                @p.description
                            </p>

                            <!-- Social sharing buttons -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fa fa-share"></i> Share</button>
                            <button type="button" class="btn btn-default btn-sm"><i class="fa fa-thumbs-o-up"></i> Like</button>
                            <span class="float-right text-muted">45 likes - @p.lstComm.Count comments</span>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer card-comments">
                            @foreach (var com in p.lstComm)
                            {
                                <div class="card-comment">
                                     
                                    <img class="img-circle img-sm" src="data:image/jpeg;base64,@com.user.image" alt="User Image">

                                    <div class="comment-text">
                                        <span class="username">
                                            @com.user.prenom @com.user.nom

                                            @if (userc.id == @com.user.id)
                                            {
                                                <span class="text-muted float-right">
                                                    <a href="@Url.Action("Delete", "Commentaire", new { id = @com.id })" onclick="return confirm('Are you sure you want to delete this item?');">
                                                        <i class="fas fa-trash"></i>
                                                    </a>
                                                </span>
                                                <span class="text-muted float-right">
                                                    <a href="#">
                                                        &nbsp;&nbsp;&nbsp;&nbsp;
                                                        <i class="fas fa-edit"></i>
                                                        &nbsp;&nbsp;

                                                    </a>

                                                </span>
                                            }
                                                <span class="text-muted float-right">@com.dateCreation</span>






                                            </span> 
                                        @com.description .
                                    </div>
                                </div>                       
                            } 
                            </div>
                        <!-- /.card-footer -->
                        <div class="card-footer">

                            <form class="form-horizontal" action="@Url.Action("Create", "Commentaire")"  method="get">
                                <div class="input-group input-group-sm mb-0">
                                    <img class="img-fluid img-circle img-sm" src="data:image/jpeg;base64,@userc.image" alt="Alt Text">
                                    <input id="idpub" name="idpub" value="@p.id" style="display: none;" >
                                    <input id="description" name="description" class="form-control form-control-sm" placeholder="Response">
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-danger">Commenter</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <!-- /.card-footer -->
                    </div>
                    <!-- /.card -->
                }
            </div>
         </div>
    </div>
</section>